source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'OrienteeringQuiz' do
    pod 'SwiftyJSON'
    pod 'PKHUD', :git => 'https://github.com/toyship/PKHUD.git'
    pod 'Kingfisher'
    pod 'PromiseKit/Alamofire'
    pod 'SideMenu'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end